"""empty message

Revision ID: 55afb0f224c6
Revises: 72eb5efcc4cc
Create Date: 2021-06-17 23:39:55.769588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55afb0f224c6'
down_revision = '72eb5efcc4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('favcount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
