"""empty message

Revision ID: b2c64fc0fcf9
Revises: 55afb0f224c6
Create Date: 2021-06-18 00:13:46.339297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c64fc0fcf9'
down_revision = '55afb0f224c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('favcount', sa.Integer(), nullable=True),
    sa.Column('displayName', sa.String(), nullable=True),
    sa.Column('hexS3', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
